services:
  # On remplace Bombardier par K6 pour gérer des scénarios complets
  test-scenario:
    image: grafana/k6
    depends_on:
      - backend
    volumes:
      - ./loadtest.js:/loadtest.js:ro,Z
    command: run /loadtest.js
    profiles:
      - testing
